export const skillsArray = [
    { label: "Front-End Development", value: "front-end-development" },
    { label: "Back-End Development", value: "back-end-development" },
    { label: "Full-Stack Development", value: "full-stack-development" },
    { label: "ExpressJS", value: "expressjs" },
    { label: "NextJS", value: "nextjs" },
    { label: "TypeScript", value: "typescript" },
    { label: "HTML", value: "html" },
    { label: "CSS", value: "css" },
    { label: "Javascript", value: "javascript" },
    { label: "React", value: "react" },
    { label: "Angular", value: "angular" },
    { label: "Vue.js", value: "vuejs" },
    { label: "Node.js", value: "nodejs" },
    { label: "Python", value: "python" },
    { label: "Ruby on Rails", value: "ruby-on-rails" },
    { label: "Java", value: "java" },
    { label: "PHP", value: "php" },
    { label: "Swift", value: "swift" },
    { label: "Kotlin", value: "kotlin" },
    { label: "C#", value: "csharp" },
    { label: "ASP.NET", value: "aspnet" },
    { label: "C++", value: "cplusplus" },
    { label: "C", value: "c" },
    { label: "Go", value: "go" },
    { label: "Rust", value: "rust" },
    { label: "Flutter", value: "flutter" },
    { label: "Software Engineer", value: "software-engineer" },
    { label: "IOS Developer", value: "ios-developer" },
    { label: "DevOps", value: "devops" },
    { label: "TypeScript", value: "typescript" },
    { label: "SQL", value: "sql" },
    { label: "MySQL", value: "mysql" },
    { label: "PostgreSQL", value: "postgresql" },
    { label: "MongoDB", value: "mongodb" },
    { label: "Firebase", value: "firebase" },
    { label: "Docker", value: "docker" },
    { label: "Kubernetes", value: "kubernetes" },
    { label: "AWS", value: "aws" },
    { label: "Azure", value: "azure" },
    { label: "Google Cloud", value: "google-cloud" },
    { label: "GraphQL", value: "graphql" },
    { label: "Redux", value: "redux" },
    { label: "Git", value: "git" },
    { label: "Jenkins", value: "jenkins" },
    { label: "Webpack", value: "webpack" },
    { label: "Babel", value: "babel" },
    { label: "Sass", value: "sass" },
    { label: "Less", value: "less" },
    { label: "Bootstrap", value: "bootstrap" },
    { label: "Material-UI", value: "material-ui" },
    { label: "Tailwind CSS", value: "tailwind-css" },
    { label: "Figma", value: "figma" },
    { label: "Sketch", value: "sketch" },
    { label: "Adobe XD", value: "adobe-xd" },
    { label: "InVision", value: "invision" },
    { label: "Photoshop", value: "photoshop" },
    { label: "Illustrator", value: "illustrator" },
    { label: "After Effects", value: "after-effects" },
    { label: "Premiere Pro", value: "premiere-pro" },
    { label: "UI/UX Design", value: "ui-ux-design" },
    { label: "User Research", value: "user-research" },
    { label: "Wireframing", value: "wireframing" },
    { label: "Prototyping", value: "prototyping" },
    { label: "Usability Testing", value: "usability-testing" },
    { label: "Accessibility", value: "accessibility" },
    { label: "SEO/SEM Marketing", value: "seo-sem-marketing" },
    { label: "Content Writing", value: "content-writing" },
    { label: "Copywriting", value: "copywriting" },
    { label: "Data Analysis", value: "data-analysis" },
    { label: "Project Management", value: "project-management" },
    { label: "Social Media Management", value: "social-media-management" },
    { label: "Video Editing", value: "video-editing" },
    { label: "3D Modeling", value: "3d-modeling" },
    { label: "Photography", value: "photography" },
    { label: "Translation", value: "translation" },
    { label: "Voice Over", value: "voice-over" }
];
